CREATE TABLE shop.posts (id INT PRIMARY KEY, body JSON);
CREATE TABLE shop.tags (id INT);
INSERT INTO shop.posts VALUES (1, '{"a": 1}');
CREATE FUNCTION shop.one() RETURNS INT DETERMINISTIC RETURN 1;
CREATE TRIGGER shop.tags_default BEFORE INSERT ON shop.tags FOR EACH ROW SET NEW.id = IFNULL(NEW.id, 0);
CREATE USER 'bkp'@'%' IDENTIFIED BY 'bkppw';
GRANT SELECT, SHOW VIEW, TRIGGER ON shop.* TO 'bkp'@'%';
GRANT SHOW_ROUTINE ON *.* TO 'bkp'@'%';
GRANT ALL ON `dbb\_verify\_%`.* TO 'bkp'@'%';
CREATE DATABASE fkshop;
CREATE TABLE fkshop.parent (id INT PRIMARY KEY) ENGINE=InnoDB;
CREATE TABLE fkshop.child (id INT PRIMARY KEY, pid INT, CONSTRAINT child_parent FOREIGN KEY (pid) REFERENCES fkshop.parent (id)) ENGINE=InnoDB;
INSERT INTO fkshop.parent VALUES (1);
INSERT INTO fkshop.child VALUES (1, 1);
GRANT SELECT, SHOW VIEW, TRIGGER ON fkshop.* TO 'bkp'@'%';
CREATE DATABASE fkq;
CREATE TABLE fkq.`pa``rent` (id INT PRIMARY KEY) ENGINE=InnoDB;
CREATE TABLE fkq.child (id INT PRIMARY KEY, pid INT, CONSTRAINT cq FOREIGN KEY (pid) REFERENCES fkq.`pa``rent` (id)) ENGINE=InnoDB;
INSERT INTO fkq.`pa``rent` VALUES (1);
INSERT INTO fkq.child VALUES (1, 1);
GRANT SELECT, SHOW VIEW, TRIGGER ON fkq.* TO 'bkp'@'%';
