name: gitleaks

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  scan:
    uses: roleme/workflows/.github/workflows/gitleaks-reusable.yml@c5ca0171d8bd837163aeced94a705c81998daa26 # v2.5.0
    permissions:
      contents: read
      pull-requests: read
